### ISSUE TITLE
Use subscription without implicit attach when subscribing on a channel

### ISSUE THREAD

**Issue by ttypic** [ably-labs/ably-chat-kotlin#17]
After https://github.com/ably/ably-java/issues/1027 is merged, we need to update the DefaultMessages implementation. When subscribing to the channel, we should use the `attachOnSubscribe = false` channel option to achieve this.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4978) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Fixed via https://github.com/ably-labs/ably-chat-kotlin/pull/28
