### ISSUE TITLE
[Integration Test] Implement test sandbox API

### ISSUE THREAD

**Issue by sacOO7** [ably-labs/ably-chat-kotlin#26]
- Implement test sandbox API as a part of test-suite.
- Currently, only unit tests are available, to test complex scenarios, we will need ably sandbox in place.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5014) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Based on the last discussion, the scope of this work has been significantly reduced and we will only focus on testing basic functionality of public API's using ably sandbox.

**Comment by sacOO7** [comment]
sandbox `setup` and `tearDown` involves minimal work and can be referred from https://github.com/ably-forks/laravel-echo/blob/master/tests/ably/setup/sandbox.ts

**Comment by sacOO7** [comment]
Although `chat-UTS` covers complex testing scenarios, we must set up lang. specific adapter for it. 
Also, we can't test the new public API immediately without exposing relevant methods and also depends on relevant API test availability in the `chat-UTS`. 
This task will only focus on setting up sandbox API that will be useful to test public API's without considering complex scenarios.

**Comment by sacOO7** [comment]
Need to create separate JIRA issue for `kotlin-UTS-adapter`

**Comment by lawrence-forooghian** [comment]
I’ve written some basic tests for the Swift SDK in https://github.com/ably-labs/ably-chat-swift/pull/100

**Comment by sacOO7** [comment]
Fixed via https://github.com/ably-labs/ably-chat-kotlin/pull/47
