### ISSUE TITLE
Chat Room: implement  room lifecycle spec

### ISSUE THREAD

**Issue by jamienewcomb** [ably-labs/ably-chat-kotlin#6]
Implement room lifecycle based on specification: https://sdk.ably.com/builds/ably/specification/pull/200/chat-features/ 
([Github PR](https://github.com/ably/specification/pull/200/))

Example of implementation can be found in [Chat JS SDK](https://github.com/ably/ably-chat-js/blob/main/src/core/room-lifecycle-manager.ts)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4953) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
TODO's test cases to cover when all roomlifecycle ops are implemented 

- [ ] CHA-RL1j - If the room is in the INITIALIZING status, then it must wait for the in-progress RELEASING operation from a previous room instance to complete before proceeding
- [ ] CHA-RL1i -  If a room instance is in the process of being released and cleaned up (per “CHA-RC1d”#CHA-RC1d), then the ATTACH operation of a subsequent instance of the same room shall wait for the release operation of the previous to complete before commencing.

More of the test cases will be added in the future as we progress.
